version: '3'

services:
  db:
    image: kartoza/postgis:latest
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - ./etc/pgdata/:/var/lib/postgresql/
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
