version: '3'

services:
  app:
    restart: always
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    depends_on:
      - db
    links:
      - db
    ports:
      - ${UVICORN_PORT}:${UVICORN_PORT}
    env_file:
      - .env
  db:
    image: kartoza/postgis:latest
    volumes:
      - ./etc/pgdata/:/var/lib/postgresql/
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
